/* The interface dictionary. English is the source of truth for the key set:
   `vi` is typed as Record<keyof typeof en, string>, so a key added here and
   forgotten there is a `tsc -b` error, and `npm run build` runs tsc first.

   Status vocabulary (PASS, STALE, BREAKING_API_CHANGE …) is absent on purpose:
   those are enum values from the findings schema, they appear verbatim in the
   comment posted to GitHub, and a translated dashboard label would no longer
   match the pull request it describes.

   Repo mode values (`auto`, `manual`) are absent for the same reason: they are
   the literal values an operator writes in prsentinel.yml and picks from
   Config.tsx's mode select, so Repos.tsx's "AUTO" badge (repos with no data
   yet) stays English rather than disagreeing with the YAML and the dropdown
   it mirrors. */

const en = {
  'nav.repos': 'Repos',
  'nav.config': 'Config',
  'nav.themeLight': 'Light',
  'nav.themeDark': 'Dark',
  'nav.themeSwitchToLight': 'Switch to light theme',
  'nav.themeSwitchToDark': 'Switch to dark theme',
  'nav.langSwitchToVi': 'Chuyển giao diện sang tiếng Việt',
  'nav.langSwitchToEn': 'Switch interface to English',
  'repos.bugs': '{n} bugs',
  'gate.pass': 'Clear to merge',
  'gate.warn': 'Merge with care',
  'gate.fail': 'Blocked',
  'gate.unknown': 'Not scored',
  'band.empty': 'No scored reviews yet',
  'common.loading': 'Loading',
  'common.yes': 'yes',
  'common.no': 'no',
  'common.noTitle': '(no title)',
  'citations.none': 'no evidence cited',
  'repos.error': 'Could not load repos — {detail}',
  'repos.loading': 'Loading repositories',
  'repos.title': 'Every claim, checked against the code.',
  'repos.subOne': '{n} repo reviewed',
  'repos.subMany': '{n} repos reviewed',
  'repos.subPrs': '{n} pull requests on the record',
  'repos.emptyBefore': 'No reviews yet. Run ',
  'repos.emptyAfter': ', or add a repo on the Config page and let the poller pick it up.',
  'repos.prs': '{n} PR',
  'repos.docErrors': '{n} doc errors',
  'repos.breaking': '{n} breaking',
  'repos.testGaps': '{n} test gaps',
  'repos.verified': '{score} verified',
  'repos.waitingMeta': 'Set to auto — the poller reviews its next open PR',
  'repos.searchAria': 'Filter repositories',
  'repos.searchPlaceholder': 'filter by name',
  'repos.sortAria': 'Sort repositories',
  'repos.sortPrs': 'By PRs',
  'repos.sortSpend': 'By spend',
  'repos.sortName': 'By name',
  'repos.watched': 'Watched',
  'repos.removeConfirm': 'Really remove?',
  'repos.removeAria': 'Remove {repo}',
  'repos.addAria': 'Repository to watch',
  'repo.loading': 'Loading repository',
  'repo.statusReviewed': 'Reviewed',
  'repo.statusReviewing': 'Reviewing now',
  'repo.statusNotReviewed': 'Not reviewed',
  'repo.tilePrs': 'PRs reviewed',
  'repo.tileVerified': 'Verified',
  'repo.tileVerifiedNote': 'claims backed by file:line',
  'repo.tileBugs': 'Bugs',
  'repo.tileBugsNote': 'failed claims + broken impact',
  'repo.tileDocErrors': 'Doc errors',
  'repo.tileBreaking': 'Breaking',
  'repo.tileBreakingNote': 'API + schema contracts',
  'repo.tileSpent': 'Spent',
  'repo.gateHeading': 'Merge decisions',
  'repo.openPrsHeading': 'Open pull requests',
  'repo.unreachable': 'GitHub is unreachable — showing pull requests from stored reviews only.',
  'repo.noOpenPrs': 'No open pull requests.',
  'repo.draft': 'draft',
  'repo.roundOne': '{n} round',
  'repo.roundMany': '{n} rounds',
  'repo.prBugs': '{n} bugs',
  'repo.prDocErrors': '{n} doc errors',
  'repo.prBreaking': '{n} breaking',
  'repo.reReview': 'Re-review',
  'repo.reviewNow': 'Review now',
  'repo.sectionRunning': 'Running',
  'repo.sectionBlocked': 'Blocked',
  'repo.sectionWarned': 'Warned',
  'repo.sectionPassed': 'Passed',
  'repo.sectionNotScored': 'Not scored',
  'repo.sectionNotReviewed': 'Not reviewed',
  'repo.sectionDraft': 'Drafts',
  'repo.searchAria': 'Filter pull requests',
  'repo.searchPlaceholder': 'filter by number, title, author',
  'repo.gateFilterAria': 'Filter by merge decision',
  'repo.gateFilterAll': 'All',
  'repo.answerReplies': 'Answer replies',
  'pr.loading': 'Loading the PR',
  'pr.by': 'by {author}',
  'pr.openOnGitHub': 'open on GitHub',
  'pr.notReviewed': 'This pull request has not been reviewed yet.',
  'pr.reviewing': 'Reviewing…',
  'pr.reviewNow': 'Review now',
  'pr.reReview': 'Re-review',
  'pr.answerReplies': 'Answer replies',
  'pr.tileGate': 'Gate',
  'pr.tileVerified': 'Verified',
  'pr.tileVerifiedNote': 'claims with file:line',
  'pr.tileVerdict': 'Verdict',
  'pr.tileVerdictNote': 'PR description vs code',
  'pr.tileRisk': 'Business risk',
  'pr.tileRounds': 'Rounds',
  'pr.tileCost': 'Cost',
  'pr.pipelineHeading': 'Pipeline',
  'pr.pipelineLoading': 'Loading the pipeline',
  'pr.noPipeline': 'No pipeline data for this review yet.',
  'pr.whyGate': 'Why this gate:',
  'pr.lastRun': 'last run exit {code} · {at}',
  'pr.inProgressHeading': 'Review in progress',
  'pr.starting': 'starting…',
  'pr.blockingHeading': 'Blocking ({n})',
  'pr.tabClaims': 'Claims',
  'pr.tabDocs': 'Docs',
  'pr.tabImpact': 'Impact',
  'pr.tabCallers': 'Callers',
  'pr.tabContracts': 'Contracts',
  'pr.tabCrossPr': 'Cross-PR',
  'pr.tabTests': 'Tests',
  'pr.tabThreads': 'Threads',
  'pr.tabConfirm': 'Confirm',
  'pr.tabContext': 'Context',
  'pr.blockContract': 'Contract',
  'pr.blockCaller': 'Caller',
  'pr.blockClaim': 'Claim',
  'pr.blockImpact': 'Impact',
  'pr.blockDoc': 'Doc',
  'pr.blockTest': 'Test',
  'pr.emptyClaims': 'The description made no verifiable claims.',
  'pr.emptyDocs': 'No documentation related to this change was found.',
  'pr.emptyImpact': 'No requirement was traced to this change.',
  'pr.emptyCallers': 'Nothing outside this diff calls the changed code.',
  'pr.emptyContracts': 'No API, schema, type or proto contract was touched.',
  'pr.emptyCrossPrNoCollision': 'No collision found with the open pull requests that overlap this one.',
  'pr.emptyCrossPrNotScanned': 'No overlapping open pull request was scanned.',
  'pr.emptyTests': 'No test coverage was assessed for this change.',
  'pr.emptyThreads': 'No review comments to re-check.',
  'pr.emptyConfirm': 'The reviewer had no questions for a human.',
  'pr.emptyContext': 'The whole diff went into the review — nothing was trimmed.',
  'pr.uncovered': 'uncovered: {case} → {where}',
  'pr.answered': 'answered: {answer}',
  'pr.dropped': 'dropped',
  'pr.trimmed': 'patch trimmed',
  'pr.repliesHeading': 'Replies answered',
  'graph.statusDone': 'done',
  'graph.statusRunning': 'running',
  'graph.statusFailed': 'failed',
  'graph.statusPending': 'pending',
  'graph.statusSkipped': 'skipped',
  'ws.tabOverview': 'Overview',
  'ws.tabPipeline': 'Pipeline',
  'ws.reasonsToggle': 'Show reasons ({n})',
  'ws.reasonsHide': 'Hide reasons',
  'ws.phaseStripLabel': 'Pipeline phases',
  'ws.navFindings': 'Findings',
  'ws.navFiles': 'Files',
  'ws.noFindings': 'No findings',
  'ws.collapseNav': 'Hide sidebar',
  'ws.expandNav': 'Show sidebar',
  'ws.filesViewed': '{done}/{total} viewed',
  'ws.confidence': 'confidence {pct}',
  'ws.questionsHeading': 'Questions for a human',
  'ws.prunedHeading': 'Excluded from context',
  'files.viewed': 'Viewed',
  'files.markViewed': 'Mark {path} as viewed',
  'files.summary': '{path}: +{added} −{deleted}, {findings} findings',
  'files.inFile': '{n} findings',
  'files.line': 'line {n}',
  'files.empty': 'No changed files in this snapshot.',
  'files.unanchoredHeading': 'Not anchored to the diff',
  'report.tab': 'Report',
  'report.loading': 'Loading report',
  'report.empty': 'No report yet.',
  'run.tab': 'Run',
  'run.liveHeading': 'Live log',
  'run.idle': 'No review is running.',
  'run.elapsed': 'elapsed {t}',
  'run.costHeading': 'Cost per phase',
  'run.colPhase': 'Phase',
  'run.colModel': 'Model',
  'run.colTurns': 'Turns',
  'run.colDuration': 'Duration',
  'run.colCost': 'Cost',
  'extras.ticketHeading': 'Ticket',
  'extras.neutralizedBanner': 'Suspicious instructions in this PR were neutralized before review',
  'extras.descriptionHeading': 'Draft description',
  'graph.phase.snapshot': 'Snapshot',
  'graph.phase.siblings': 'Sibling scan',
  'graph.phase.describe': 'Describe',
  'graph.phase.claims': 'Claims',
  'graph.phase.followup': 'Replies',
  'graph.phase.verify': 'Verify',
  'graph.phase.remediate': 'Doc fixes',
  'graph.phase.poc': 'PoC tests',
  'graph.phase.score': 'Score',
  'graph.phase.ask': 'Confirm',
  'graph.phase.report': 'Report',
  'graph.metric.files': 'files',
  'graph.metric.commits': 'commits',
  'graph.metric.pruned': 'pruned',
  'graph.metric.scanned': 'scanned',
  'graph.metric.overlapping': 'overlapping',
  'graph.metric.claims': 'claims',
  'graph.metric.docs': 'docs',
  'graph.metric.callers': 'callers',
  'graph.metric.contracts': 'contracts',
  'graph.metric.gate': 'gate',
  'graph.metric.verified': 'verified',
  'graph.metric.answered': 'answered',
  'graph.metric.open': 'open',
  'graph.metric.patches': 'patches',
  'graph.metric.tests': 'tests',
  'graph.metric.replies': 'replies',
  'config.errorAfter': ' — create ',
  'config.errorMid': ' next to the repo, or point ',
  'config.errorEnd': ' at it.',
  'config.loading': 'Loading configuration',
  'config.title': 'What the poller watches',
  'config.tileOrg': 'Org',
  'config.tilePollEvery': 'Poll every',
  'config.tileGateAt': 'Gate at',
  'config.tileGateNote': 'minimum verification score',
  'config.tilePostsComments': 'Posts comments',
  'config.tileDocPrs': 'Writes doc PRs',
  'config.tileRewritesBody': 'Rewrites PR body',
  'config.providerHeading': 'Model provider',
  'config.noKeyBefore': 'No key for ',
  'config.noKeyMid': ' — set ',
  'config.noKeyAfter': ' in ',
  'config.noKeyEnd': '. Reviews will refuse to start until it is there.',
  'config.tileProvider': 'Provider',
  'config.tileDeepDive': 'Deep dive',
  'config.tileClaims': 'Claims',
  'config.tileSchema': 'Schema',
  'config.schemaEnforced': 'enforced',
  'config.schemaPrompted': 'prompted',
  'config.schemaEnforcedNote': 'the API validates the JSON',
  'config.schemaPromptedNote': 'the reply is parsed and repaired',
  'config.tileKey': 'Key',
  'config.keySet': 'set',
  'config.keyMissing': 'missing',
  'config.tileCosts': 'Costs',
  'config.costsTracked': 'tracked',
  'config.costsUnknown': 'unknown',
  'config.costsUnknownNote': 'budget caps do not apply',
  'config.tokensNote': 'tokens are read from the environment only',
  'config.languageHeading': 'Language',
  'config.uiLanguage': 'Interface',
  'config.uiLanguageNote': 'this browser only — it does not change what the agent writes',
  'config.reviewLanguage': 'Review output',
  'config.reviewLanguageNote': 'written to the config file; applies to every review, including CI',
  'config.languageFootnote': 'Status codes (PASS, STALE, BROKEN…) stay English so the dashboard matches the comment posted on GitHub.',
  'config.uiLanguageAria': 'Interface language',
  'config.reviewLanguageAria': 'Review output language',
  'config.repoPlaceholderOrg': 'repo-name or owner/repo',
  'config.watchRepo': 'Watch repo',
  'config.modeAria': 'Mode for {repo}',
  'config.remove': 'Remove',
  'lang.en': 'English',
  'lang.vi': 'Tiếng Việt',
}

const vi: Record<keyof typeof en, string> = {
  'nav.repos': 'Kho mã',
  'nav.config': 'Cấu hình',
  'nav.themeLight': 'Sáng',
  'nav.themeDark': 'Tối',
  'nav.themeSwitchToLight': 'Chuyển sang giao diện sáng',
  'nav.themeSwitchToDark': 'Chuyển sang giao diện tối',
  'nav.langSwitchToVi': 'Chuyển giao diện sang tiếng Việt',
  'nav.langSwitchToEn': 'Switch interface to English',
  'repos.bugs': '{n} lỗi',
  'gate.pass': 'Sẵn sàng merge',
  'gate.warn': 'Merge có cân nhắc',
  'gate.fail': 'Bị chặn',
  'gate.unknown': 'Chưa chấm điểm',
  'band.empty': 'Chưa có review nào được chấm điểm',
  'common.loading': 'Đang tải',
  'common.yes': 'có',
  'common.no': 'không',
  'common.noTitle': '(không có tiêu đề)',
  'citations.none': 'không có bằng chứng nào được dẫn',
  'repos.error': 'Không tải được danh sách kho mã — {detail}',
  'repos.loading': 'Đang tải danh sách kho mã',
  'repos.title': 'Mọi tuyên bố đều được đối chiếu với code.',
  'repos.subOne': '{n} kho mã đã review',
  'repos.subMany': '{n} kho mã đã review',
  'repos.subPrs': '{n} pull request trong hồ sơ',
  'repos.emptyBefore': 'Chưa có review nào. Chạy ',
  'repos.emptyAfter': ', hoặc thêm một kho mã ở trang Cấu hình rồi để bộ quét tự nhận.',
  'repos.prs': '{n} PR',
  'repos.docErrors': '{n} lỗi tài liệu',
  'repos.breaking': '{n} phá vỡ tương thích',
  'repos.testGaps': '{n} lỗ hổng test',
  'repos.verified': '{score} đã xác minh',
  'repos.waitingMeta': 'Đặt chế độ auto — bộ quét sẽ review PR mở tiếp theo',
  'repos.searchAria': 'Lọc danh sách repo',
  'repos.searchPlaceholder': 'lọc theo tên',
  'repos.sortAria': 'Sắp xếp repo',
  'repos.sortPrs': 'Theo số PR',
  'repos.sortSpend': 'Theo chi phí',
  'repos.sortName': 'Theo tên',
  'repos.watched': 'Đang theo dõi',
  'repos.removeConfirm': 'Bỏ theo dõi thật?',
  'repos.removeAria': 'Bỏ theo dõi {repo}',
  'repos.addAria': 'Repo cần theo dõi',
  'repo.loading': 'Đang tải kho mã',
  'repo.statusReviewed': 'Đã review',
  'repo.statusReviewing': 'Đang review',
  'repo.statusNotReviewed': 'Chưa review',
  'repo.tilePrs': 'PR đã review',
  'repo.tileVerified': 'Đã xác minh',
  'repo.tileVerifiedNote': 'tuyên bố có dẫn file:line',
  'repo.tileBugs': 'Lỗi',
  'repo.tileBugsNote': 'tuyên bố sai + tác động hỏng',
  'repo.tileDocErrors': 'Lỗi tài liệu',
  'repo.tileBreaking': 'Phá vỡ tương thích',
  'repo.tileBreakingNote': 'hợp đồng API + schema',
  'repo.tileSpent': 'Đã chi',
  'repo.gateHeading': 'Quyết định merge',
  'repo.openPrsHeading': 'Pull request đang mở',
  'repo.unreachable': 'Không kết nối được GitHub — chỉ hiện pull request từ review đã lưu.',
  'repo.noOpenPrs': 'Không có pull request nào đang mở.',
  'repo.draft': 'nháp',
  'repo.roundOne': '{n} vòng',
  'repo.roundMany': '{n} vòng',
  'repo.prBugs': '{n} lỗi',
  'repo.prDocErrors': '{n} lỗi tài liệu',
  'repo.prBreaking': '{n} phá vỡ tương thích',
  'repo.reReview': 'Review lại',
  'repo.reviewNow': 'Review ngay',
  'repo.sectionRunning': 'Đang chạy',
  'repo.sectionBlocked': 'Bị chặn',
  'repo.sectionWarned': 'Có cảnh báo',
  'repo.sectionPassed': 'Đạt',
  'repo.sectionNotScored': 'Chưa chấm điểm',
  'repo.sectionNotReviewed': 'Chưa review',
  'repo.sectionDraft': 'Bản nháp',
  'repo.searchAria': 'Lọc danh sách PR',
  'repo.searchPlaceholder': 'lọc theo số, tiêu đề, tác giả',
  'repo.gateFilterAria': 'Lọc theo quyết định merge',
  'repo.gateFilterAll': 'Tất cả',
  'repo.answerReplies': 'Trả lời phản hồi',
  'pr.loading': 'Đang tải PR',
  'pr.by': 'bởi {author}',
  'pr.openOnGitHub': 'mở trên GitHub',
  'pr.notReviewed': 'Pull request này chưa được review.',
  'pr.reviewing': 'Đang review…',
  'pr.reviewNow': 'Review ngay',
  'pr.reReview': 'Review lại',
  'pr.answerReplies': 'Trả lời phản hồi',
  'pr.tileGate': 'Cổng merge',
  'pr.tileVerified': 'Đã xác minh',
  'pr.tileVerifiedNote': 'tuyên bố có file:line',
  'pr.tileVerdict': 'Kết luận',
  'pr.tileVerdictNote': 'mô tả PR đối chiếu code',
  'pr.tileRisk': 'Rủi ro nghiệp vụ',
  'pr.tileRounds': 'Số vòng',
  'pr.tileCost': 'Chi phí',
  'pr.pipelineHeading': 'Quy trình',
  'pr.pipelineLoading': 'Đang tải quy trình',
  'pr.noPipeline': 'Chưa có dữ liệu quy trình cho review này.',
  'pr.whyGate': 'Vì sao có kết quả này:',
  'pr.lastRun': 'lần chạy trước thoát {code} · {at}',
  'pr.inProgressHeading': 'Đang review',
  'pr.starting': 'đang khởi động…',
  'pr.blockingHeading': 'Chặn merge ({n})',
  'pr.tabClaims': 'Tuyên bố',
  'pr.tabDocs': 'Tài liệu',
  'pr.tabImpact': 'Tác động',
  'pr.tabCallers': 'Nơi gọi',
  'pr.tabContracts': 'Hợp đồng',
  'pr.tabCrossPr': 'Liên PR',
  'pr.tabTests': 'Test',
  'pr.tabThreads': 'Thảo luận',
  'pr.tabConfirm': 'Xác nhận',
  'pr.tabContext': 'Ngữ cảnh',
  'pr.blockContract': 'Hợp đồng',
  'pr.blockCaller': 'Nơi gọi',
  'pr.blockClaim': 'Tuyên bố',
  'pr.blockImpact': 'Tác động',
  'pr.blockDoc': 'Tài liệu',
  'pr.blockTest': 'Test',
  'pr.emptyClaims': 'Mô tả không đưa ra tuyên bố nào kiểm chứng được.',
  'pr.emptyDocs': 'Không tìm thấy tài liệu nào liên quan tới thay đổi này.',
  'pr.emptyImpact': 'Không truy được yêu cầu nào tới thay đổi này.',
  'pr.emptyCallers': 'Không có chỗ nào ngoài diff này gọi tới code đã đổi.',
  'pr.emptyContracts': 'Không đụng tới hợp đồng API, schema, kiểu hay proto nào.',
  'pr.emptyCrossPrNoCollision': 'Không phát hiện va chạm với pull request đang mở nào trùng phạm vi với PR này.',
  'pr.emptyCrossPrNotScanned': 'Chưa quét pull request đang mở nào có phần trùng lặp.',
  'pr.emptyTests': 'Chưa đánh giá độ phủ test cho thay đổi này.',
  'pr.emptyThreads': 'Không có comment review nào cần kiểm tra lại.',
  'pr.emptyConfirm': 'Reviewer không có câu hỏi nào cho người.',
  'pr.emptyContext': 'Toàn bộ diff đã vào review — không cắt bỏ gì.',
  'pr.uncovered': 'chưa phủ: {case} → {where}',
  'pr.answered': 'đã trả lời: {answer}',
  'pr.dropped': 'đã bỏ',
  'pr.trimmed': 'đã cắt bớt patch',
  'pr.repliesHeading': 'Phản hồi đã trả lời',
  'graph.statusDone': 'xong',
  'graph.statusRunning': 'đang chạy',
  'graph.statusFailed': 'lỗi',
  'graph.statusPending': 'chờ',
  'graph.statusSkipped': 'bỏ qua',
  'ws.tabOverview': 'Tổng quan',
  'ws.tabPipeline': 'Pipeline',
  'ws.reasonsToggle': 'Xem lý do ({n})',
  'ws.reasonsHide': 'Thu gọn lý do',
  'ws.phaseStripLabel': 'Các phase của pipeline',
  'ws.navFindings': 'Phát hiện',
  'ws.navFiles': 'File',
  'ws.noFindings': 'Không có phát hiện nào',
  'ws.collapseNav': 'Ẩn sidebar',
  'ws.expandNav': 'Hiện sidebar',
  'ws.filesViewed': '{done}/{total} đã xem',
  'ws.confidence': 'độ tin cậy {pct}',
  'ws.questionsHeading': 'Câu hỏi cần người trả lời',
  'ws.prunedHeading': 'Bị loại khỏi ngữ cảnh review',
  'files.viewed': 'Đã xem',
  'files.markViewed': 'Đánh dấu {path} đã xem',
  'files.summary': '{path}: +{added} −{deleted}, {findings} phát hiện',
  'files.inFile': '{n} phát hiện',
  'files.line': 'dòng {n}',
  'files.empty': 'Snapshot này không có file thay đổi.',
  'files.unanchoredHeading': 'Chưa gắn được vào diff',
  'report.tab': 'Báo cáo',
  'report.loading': 'Đang tải báo cáo',
  'report.empty': 'Chưa có báo cáo.',
  'run.tab': 'Lần chạy',
  'run.liveHeading': 'Log trực tiếp',
  'run.idle': 'Không có review nào đang chạy.',
  'run.elapsed': 'đã chạy {t}',
  'run.costHeading': 'Chi phí theo phase',
  'run.colPhase': 'Phase',
  'run.colModel': 'Model',
  'run.colTurns': 'Số lượt',
  'run.colDuration': 'Thời gian',
  'run.colCost': 'Chi phí',
  'extras.ticketHeading': 'Ticket',
  'extras.neutralizedBanner': 'Nội dung nghi là prompt injection trong PR đã được vô hiệu trước khi review',
  'extras.descriptionHeading': 'Bản nháp mô tả PR',
  'graph.phase.snapshot': 'Ảnh chụp',
  'graph.phase.siblings': 'Quét PR liên quan',
  'graph.phase.describe': 'Mô tả',
  'graph.phase.claims': 'Tuyên bố',
  'graph.phase.followup': 'Phản hồi',
  'graph.phase.verify': 'Xác minh',
  'graph.phase.remediate': 'Sửa tài liệu',
  'graph.phase.poc': 'Test PoC',
  'graph.phase.score': 'Chấm điểm',
  'graph.phase.ask': 'Xác nhận',
  'graph.phase.report': 'Báo cáo',
  'graph.metric.files': 'tệp',
  'graph.metric.commits': 'commit',
  'graph.metric.pruned': 'đã cắt',
  'graph.metric.scanned': 'đã quét',
  'graph.metric.overlapping': 'trùng lặp',
  'graph.metric.claims': 'tuyên bố',
  'graph.metric.docs': 'tài liệu',
  'graph.metric.callers': 'nơi gọi',
  'graph.metric.contracts': 'hợp đồng',
  'graph.metric.gate': 'cổng',
  'graph.metric.verified': 'đã xác minh',
  'graph.metric.answered': 'đã trả lời',
  'graph.metric.open': 'còn mở',
  'graph.metric.patches': 'bản vá',
  'graph.metric.tests': 'test',
  'graph.metric.replies': 'phản hồi',
  'config.errorAfter': ' — tạo ',
  'config.errorMid': ' cạnh kho mã, hoặc trỏ ',
  'config.errorEnd': ' tới nó.',
  'config.loading': 'Đang tải cấu hình',
  'config.title': 'Bộ quét đang theo dõi những gì',
  'config.tileOrg': 'Tổ chức',
  'config.tilePollEvery': 'Chu kỳ quét',
  'config.tileGateAt': 'Ngưỡng cổng',
  'config.tileGateNote': 'điểm xác minh tối thiểu',
  'config.tilePostsComments': 'Đăng comment',
  'config.tileDocPrs': 'Mở PR sửa tài liệu',
  'config.tileRewritesBody': 'Viết lại mô tả PR',
  'config.providerHeading': 'Nhà cung cấp model',
  'config.noKeyBefore': 'Chưa có khoá cho ',
  'config.noKeyMid': ' — đặt ',
  'config.noKeyAfter': ' trong ',
  'config.noKeyEnd': '. Review sẽ không chạy cho tới khi có khoá.',
  'config.tileProvider': 'Nhà cung cấp',
  'config.tileDeepDive': 'Phân tích sâu',
  'config.tileClaims': 'Tuyên bố',
  'config.tileSchema': 'Schema',
  'config.schemaEnforced': 'bắt buộc',
  'config.schemaPrompted': 'nhắc qua prompt',
  'config.schemaEnforcedNote': 'API tự kiểm tra JSON',
  'config.schemaPromptedNote': 'phản hồi được phân tích và sửa lại',
  'config.tileKey': 'Khoá',
  'config.keySet': 'đã có',
  'config.keyMissing': 'thiếu',
  'config.tileCosts': 'Chi phí',
  'config.costsTracked': 'có theo dõi',
  'config.costsUnknown': 'không rõ',
  'config.costsUnknownNote': 'không áp được hạn mức ngân sách',
  'config.tokensNote': 'token chỉ đọc từ biến môi trường',
  'config.languageHeading': 'Ngôn ngữ',
  'config.uiLanguage': 'Giao diện',
  'config.uiLanguageNote': 'chỉ trình duyệt này — không đổi thứ agent viết ra',
  'config.reviewLanguage': 'Output review',
  'config.reviewLanguageNote': 'ghi vào file cấu hình; áp dụng cho mọi review, kể cả CI',
  'config.languageFootnote': 'Mã trạng thái (PASS, STALE, BROKEN…) luôn giữ tiếng Anh để dashboard khớp với comment đăng trên GitHub.',
  'config.uiLanguageAria': 'Ngôn ngữ giao diện',
  'config.reviewLanguageAria': 'Ngôn ngữ output review',
  'config.repoPlaceholderOrg': 'tên-kho hoặc owner/repo',
  'config.watchRepo': 'Theo dõi kho',
  'config.modeAria': 'Chế độ cho {repo}',
  'config.remove': 'Bỏ theo dõi',
  'lang.en': 'English',
  'lang.vi': 'Tiếng Việt',
}

export type Key = keyof typeof en
export type Vars = Record<string, string | number>

// Annotated rather than inferred so TABLES[lang][key] is `string`, not the
// union of en's literal types with vi's `string`.
export const TABLES: Record<'en' | 'vi', Record<Key, string>> = { en, vi }

/** Phase and metric labels arrive from the server at runtime (see
 *  web/metrics.py PHASES), so unlike everything above they cannot be a total
 *  map checked by the compiler. An id with no entry falls back to the server's
 *  English string. tests/test_ui_strings.py is what stops that going unnoticed. */
export function lookup(lang: 'en' | 'vi', key: string, fallback: string): string {
  const table = TABLES[lang] as Record<string, string | undefined>
  return table[key] ?? fallback
}
