/* The interface dictionary. English is the source of truth for the key set:
   `vi` is typed as Record<keyof typeof en, string>, so a key added here and
   forgotten there is a `tsc -b` error, and `npm run build` runs tsc first.

   Status vocabulary (PASS, STALE, BREAKING_API_CHANGE …) is absent on purpose:
   those are enum values from the findings schema, they appear verbatim in the
   comment posted to GitHub, and a translated dashboard label would no longer
   match the pull request it describes.

   Repo mode values (`auto`, `manual`) are absent for the same reason: they are
   the literal values an operator writes in prsentinel.yml, so the mode badge
   stays English rather than disagreeing with the YAML.

   VIETNAMESE GLOSSARY — meaning-based, written for Vietnamese developers, not
   word-by-word. Loanwords a VN dev says in English STAY English: PR, repo,
   review, merge, commit, diff, patch, snapshot, claim, contract, caller, test,
   gate, breaking change, docs, thread, pipeline, phase, log, trace,
   transcript, workspace, session, schema, parse, model, provider, token,
   API key, exit code, comment, ticket, CI, sidebar, file.
   Translated terms stay consistent everywhere: bằng chứng (evidence),
   kết luận (verdict), tác động (impact), rủi ro nghiệp vụ (business risk),
   đã xác minh (verified), đã xem (viewed), thiếu test (test gap),
   chặn merge (blocking), phát hiện (finding).
   Standardized: "PR đang mở" (never "pull request đang mở"). */

const en = {
  'nav.repos': 'Repos',
  'nav.config': 'Config',
  'nav.themeLight': 'Light',
  'nav.themeDark': 'Dark',
  'nav.themeSwitchToLight': 'Switch to light theme',
  'nav.themeSwitchToDark': 'Switch to dark theme',
  'nav.langSwitchToVi': 'Chuyển giao diện sang tiếng Việt',
  'nav.langSwitchToEn': 'Switch interface to English',
  'repos.bugs': '{n} bugs',
  'gate.pass': 'Clear to merge',
  'gate.warn': 'Merge with care',
  'gate.fail': 'Blocked',
  'gate.unknown': 'Not scored',
  'band.empty': 'No scored reviews yet',
  'common.loading': 'Loading',
  'common.yes': 'yes',
  'common.no': 'no',
  'common.noTitle': '(no title)',
  'citations.none': 'no evidence cited',
  'repos.error': 'Could not load repos — {detail}',
  'repos.loading': 'Loading repositories',
  'repos.title': 'Every claim, checked against the code.',
  'repos.subOne': '{n} repo reviewed',
  'repos.subMany': '{n} repos reviewed',
  'repos.subPrs': '{n} pull requests on the record',
  'repos.emptyBefore': 'No reviews yet. Run ',
  'repos.emptyAfter': ', or add a repo above and let the poller pick it up.',
  'repos.prs': '{n} PR',
  'repos.docErrors': '{n} doc errors',
  'repos.breaking': '{n} breaking',
  'repos.testGaps': '{n} test gaps',
  'repos.verified': '{score} verified',
  'repos.waitingMeta': 'Set to auto — the poller reviews its next open PR',
  'repos.searchAria': 'Filter repositories',
  'repos.searchPlaceholder': 'filter by name',
  'repos.sortAria': 'Sort repositories',
  'repos.sortPrs': 'By PRs',
  'repos.sortSpend': 'By spend',
  'repos.sortName': 'By name',
  'repos.watched': 'Watched',
  'repos.removeConfirm': 'Really remove?',
  'repos.removeAria': 'Remove {repo}',
  'repos.addAria': 'Repository to watch',
  'repo.loading': 'Loading repository',
  'repo.statusReviewed': 'Reviewed',
  'repo.statusReviewing': 'Reviewing now',
  'repo.statusNotReviewed': 'Not reviewed',
  'repo.tilePrs': 'PRs reviewed',
  'repo.tileVerified': 'Verified',
  'repo.tileVerifiedNote': 'claims backed by file:line',
  'repo.tileBugs': 'Bugs',
  'repo.tileBugsNote': 'failed claims + broken impact',
  'repo.tileDocErrors': 'Doc errors',
  'repo.tileBreaking': 'Breaking',
  'repo.tileBreakingNote': 'API + schema contracts',
  'repo.tileSpent': 'Spent',
  'repo.gateHeading': 'Merge decisions',
  'repo.unreachable': 'GitHub is unreachable — showing pull requests from stored reviews only.',
  'repo.noOpenPrs': 'No open pull requests.',
  'repo.draft': 'draft',
  'repo.roundOne': '{n} round',
  'repo.roundMany': '{n} rounds',
  'repo.prBugs': '{n} bugs',
  'repo.prDocErrors': '{n} doc errors',
  'repo.prBreaking': '{n} breaking',
  'repo.reReview': 'Re-review',
  'repo.reviewNow': 'Review now',
  'repo.sectionRunning': 'Running',
  'repo.sectionBlocked': 'Blocked',
  'repo.sectionWarned': 'Warned',
  'repo.sectionPassed': 'Passed',
  'repo.sectionNotScored': 'Not scored',
  'repo.sectionNotReviewed': 'Not reviewed',
  'repo.sectionDraft': 'Drafts',
  'repo.searchAria': 'Filter pull requests',
  'repo.searchPlaceholder': 'filter by number, title, author',
  'repo.gateFilterAria': 'Filter by merge decision',
  'repo.gateFilterAll': 'All',
  'repo.answerReplies': 'Answer replies',
  'pr.loading': 'Loading the PR',
  'pr.by': 'by {author}',
  'pr.openOnGitHub': 'open on GitHub',
  'pr.notReviewed': 'This pull request has not been reviewed yet.',
  'pr.reviewing': 'Reviewing…',
  'pr.reviewNow': 'Review now',
  'pr.reReview': 'Re-review',
  'pr.answerReplies': 'Answer replies',
  'pr.tileGate': 'Gate',
  'pr.tileVerified': 'Verified',
  'pr.tileVerifiedNote': 'claims with file:line',
  'pr.tileVerdict': 'Verdict',
  'pr.tileVerdictNote': 'PR description vs code',
  'pr.tileRisk': 'Business risk',
  'pr.tileRounds': 'Rounds',
  'pr.tileCost': 'Cost',
  'pr.pipelineLoading': 'Loading the pipeline',
  'pr.noPipeline': 'No pipeline data for this review yet.',
  'pr.whyGate': 'Why this gate:',
  'pr.lastRun': 'last run exit {code} · {at}',
  'pr.starting': 'starting…',
  'pr.blockingHeading': 'Blocking ({n})',
  'pr.tabClaims': 'Claims',
  'pr.tabDocs': 'Docs',
  'pr.tabImpact': 'Impact',
  'pr.tabCallers': 'Callers',
  'pr.tabContracts': 'Contracts',
  'pr.tabCrossPr': 'Cross-PR',
  'pr.tabTests': 'Tests',
  'pr.tabThreads': 'Threads',
  'pr.blockContract': 'Contract',
  'pr.blockCaller': 'Caller',
  'pr.blockClaim': 'Claim',
  'pr.blockImpact': 'Impact',
  'pr.blockDoc': 'Doc',
  'pr.blockTest': 'Test',
  'pr.emptyConfirm': 'The reviewer had no questions for a human.',
  'pr.answered': 'answered: {answer}',
  'pr.dropped': 'dropped',
  'pr.trimmed': 'patch trimmed',
  'pr.repliesHeading': 'Replies answered',
  'graph.statusDone': 'done',
  'graph.statusRunning': 'running',
  'graph.statusFailed': 'failed',
  'graph.statusPending': 'pending',
  'graph.statusSkipped': 'skipped',
  'ws.tabOverview': 'Overview',
  'ws.tabPipeline': 'Pipeline',
  'ws.reasonsToggle': 'Show reasons ({n})',
  'ws.reasonsHide': 'Hide reasons',
  'ws.phaseStripLabel': 'Pipeline phases',
  'ws.navFindings': 'Findings',
  'ws.navFiles': 'Files',
  'ws.noFindings': 'No findings',
  'ws.collapseNav': 'Hide sidebar',
  'ws.expandNav': 'Show sidebar',
  'ws.filesViewed': '{done}/{total} viewed',
  'ws.jumpTo': 'Jump to {ref}',
  'ws.peekLoading': 'Loading source',
  'ws.peekUnavailable': 'Workspace not available for this session — open on GitHub instead.',
  'ws.peekClose': 'Close preview',
  'ws.kbdHint': 'j/k next/prev finding · v mark file viewed · Esc clear',
  'ws.confidence': 'confidence {pct}',
  'ws.questionsHeading': 'Questions for a human',
  'ws.prunedHeading': 'Excluded from context',
  'files.viewed': 'Viewed',
  'files.markViewed': 'Mark {path} as viewed',
  'files.summary': '{path}: +{added} −{deleted}, {findings} findings',
  'files.inFile': '{n} findings',
  'files.empty': 'No changed files in this snapshot.',
  'files.unanchoredHeading': 'Not anchored to the diff',
  'files.noPatch': 'No text diff (rename or binary change)',
  'files.rawPatch': 'Showing raw patch — hunk headers could not be parsed',
  'files.patchTruncated': 'Patch truncated — {n} more lines on GitHub',
  'files.diffModeLabel': 'Diff layout',
  'files.split': 'Split',
  'files.unified': 'Unified',
  'report.tab': 'Report',
  'report.loading': 'Loading report',
  'report.empty': 'No report yet.',
  'run.tab': 'Run',
  'run.liveHeading': 'Live log',
  'run.idle': 'No review is running.',
  'run.elapsed': 'elapsed {t}',
  'run.costHeading': 'Cost per phase',
  'run.colPhase': 'Phase',
  'run.colModel': 'Model',
  'run.colTurns': 'Turns',
  'run.colDuration': 'Duration',
  'run.colCost': 'Cost',
  'extras.pocHeading': 'Proof-of-failure test',
  'extras.pocWhy': 'Why it fails',
  'extras.copy': 'Copy',
  'extras.copied': 'Copied',
  'extras.patchHeading': 'Suggested doc fix',
  'extras.patchOld': 'Current',
  'extras.patchNew': 'Suggested',
  'trace.heading': 'Agent trace',
  'trace.empty': 'No transcripts for this session.',
  'extras.ticketHeading': 'Ticket',
  'extras.neutralizedBanner': 'Suspicious instructions in this PR were neutralized before review',
  'extras.descriptionHeading': 'Draft description',
  'graph.phase.snapshot': 'Snapshot',
  'graph.phase.siblings': 'Sibling scan',
  'graph.phase.describe': 'Describe',
  'graph.phase.claims': 'Claims',
  'graph.phase.followup': 'Replies',
  'graph.phase.verify': 'Verify',
  'graph.phase.remediate': 'Doc fixes',
  'graph.phase.poc': 'PoC tests',
  'graph.phase.score': 'Score',
  'graph.phase.ask': 'Confirm',
  'graph.phase.report': 'Report',
  'graph.metric.files': 'files',
  'graph.metric.commits': 'commits',
  'graph.metric.pruned': 'pruned',
  'graph.metric.scanned': 'scanned',
  'graph.metric.overlapping': 'overlapping',
  'graph.metric.claims': 'claims',
  'graph.metric.docs': 'docs',
  'graph.metric.callers': 'callers',
  'graph.metric.contracts': 'contracts',
  'graph.metric.gate': 'gate',
  'graph.metric.verified': 'verified',
  'graph.metric.answered': 'answered',
  'graph.metric.open': 'open',
  'graph.metric.patches': 'patches',
  'graph.metric.tests': 'tests',
  'graph.metric.replies': 'replies',
  'config.errorAfter': ' — create ',
  'config.errorMid': ' next to the repo, or point ',
  'config.errorEnd': ' at it.',
  'config.loading': 'Loading configuration',
  'config.title': 'What the poller watches',
  'config.tileOrg': 'Org',
  'config.tilePollEvery': 'Poll every',
  'config.tileGateAt': 'Gate at',
  'config.tileGateNote': 'minimum verification score',
  'config.tilePostsComments': 'Posts comments',
  'config.tileDocPrs': 'Writes doc PRs',
  'config.tileRewritesBody': 'Rewrites PR body',
  'config.providerHeading': 'Model provider',
  'config.noKeyBefore': 'No key for ',
  'config.noKeyMid': ' — set ',
  'config.noKeyAfter': ' in ',
  'config.noKeyEnd': '. Reviews will refuse to start until it is there.',
  'config.tileProvider': 'Provider',
  'config.tileDeepDive': 'Deep dive',
  'config.tileClaims': 'Claims',
  'config.tileSchema': 'Schema',
  'config.schemaEnforced': 'enforced',
  'config.schemaPrompted': 'prompted',
  'config.schemaEnforcedNote': 'the API validates the JSON',
  'config.schemaPromptedNote': 'the reply is parsed and repaired',
  'config.tileKey': 'Key',
  'config.keySet': 'set',
  'config.keyMissing': 'missing',
  'config.tileCosts': 'Costs',
  'config.costsTracked': 'tracked',
  'config.costsUnknown': 'unknown',
  'config.costsUnknownNote': 'budget caps do not apply',
  'config.tokensNote': 'tokens are read from the environment only',
  'config.languageHeading': 'Language',
  'config.uiLanguage': 'Interface',
  'config.uiLanguageNote': 'this browser only — it does not change what the agent writes',
  'config.reviewLanguage': 'Review output',
  'config.reviewLanguageNote': 'written to the config file; applies to every review, including CI',
  'config.languageFootnote': 'Status codes (PASS, STALE, BROKEN…) stay English so the dashboard matches the comment posted on GitHub.',
  'config.uiLanguageAria': 'Interface language',
  'config.reviewLanguageAria': 'Review output language',
  'config.repoPlaceholderOrg': 'repo-name or owner/repo',
  'config.watchRepo': 'Watch repo',
  'config.modeAria': 'Mode for {repo}',
  'config.remove': 'Remove',
  'lang.en': 'English',
  'lang.vi': 'Tiếng Việt',
}

const vi: Record<keyof typeof en, string> = {
  'nav.repos': 'Repo',
  'nav.config': 'Cấu hình',
  'nav.themeLight': 'Sáng',
  'nav.themeDark': 'Tối',
  'nav.themeSwitchToLight': 'Chuyển sang giao diện sáng',
  'nav.themeSwitchToDark': 'Chuyển sang giao diện tối',
  'nav.langSwitchToVi': 'Chuyển giao diện sang tiếng Việt',
  'nav.langSwitchToEn': 'Switch interface to English',
  'repos.bugs': '{n} lỗi',
  'gate.pass': 'Sẵn sàng merge',
  'gate.warn': 'Cân nhắc khi merge',
  'gate.fail': 'Bị chặn',
  'gate.unknown': 'Chưa chấm điểm',
  'band.empty': 'Chưa có review nào được chấm điểm',
  'common.loading': 'Đang tải',
  'common.yes': 'có',
  'common.no': 'không',
  'common.noTitle': '(không có tiêu đề)',
  'citations.none': 'chưa dẫn bằng chứng',
  'repos.error': 'Không tải được danh sách repo — {detail}',
  'repos.loading': 'Đang tải danh sách repo',
  'repos.title': 'Mọi claim đều được đối chiếu với code.',
  'repos.subOne': '{n} repo đã review',
  'repos.subMany': '{n} repo đã review',
  'repos.subPrs': '{n} PR đã có hồ sơ review',
  'repos.emptyBefore': 'Chưa có review nào. Chạy ',
  'repos.emptyAfter': ', hoặc thêm repo ở ô phía trên để hệ thống tự nhận và review.',
  'repos.prs': '{n} PR',
  'repos.docErrors': '{n} lỗi docs',
  'repos.breaking': '{n} breaking change',
  'repos.testGaps': '{n} chỗ thiếu test',
  'repos.verified': '{score} đã xác minh',
  'repos.waitingMeta': 'Ở chế độ auto — PR mở tiếp theo sẽ tự động được review',
  'repos.searchAria': 'Lọc danh sách repo',
  'repos.searchPlaceholder': 'lọc theo tên',
  'repos.sortAria': 'Sắp xếp repo',
  'repos.sortPrs': 'Theo số PR',
  'repos.sortSpend': 'Theo chi phí',
  'repos.sortName': 'Theo tên',
  'repos.watched': 'Đang theo dõi',
  'repos.removeConfirm': 'Chắc chắn bỏ theo dõi?',
  'repos.removeAria': 'Bỏ theo dõi {repo}',
  'repos.addAria': 'Repo cần theo dõi',
  'repo.loading': 'Đang tải repo',
  'repo.statusReviewed': 'Đã review',
  'repo.statusReviewing': 'Đang review',
  'repo.statusNotReviewed': 'Chưa review',
  'repo.tilePrs': 'PR đã review',
  'repo.tileVerified': 'Đã xác minh',
  'repo.tileVerifiedNote': 'claim có dẫn chứng file:line',
  'repo.tileBugs': 'Lỗi',
  'repo.tileBugsNote': 'claim sai + tác động bị hỏng',
  'repo.tileDocErrors': 'Lỗi docs',
  'repo.tileBreaking': 'Breaking',
  'repo.tileBreakingNote': 'contract API + schema',
  'repo.tileSpent': 'Đã chi',
  'repo.gateHeading': 'Quyết định merge',
  'repo.unreachable': 'Không kết nối được GitHub — chỉ hiện PR từ những review đã lưu.',
  'repo.noOpenPrs': 'Không có PR nào đang mở.',
  'repo.draft': 'nháp',
  'repo.roundOne': '{n} vòng',
  'repo.roundMany': '{n} vòng',
  'repo.prBugs': '{n} lỗi',
  'repo.prDocErrors': '{n} lỗi docs',
  'repo.prBreaking': '{n} breaking',
  'repo.reReview': 'Review lại',
  'repo.reviewNow': 'Review ngay',
  'repo.sectionRunning': 'Đang chạy',
  'repo.sectionBlocked': 'Bị chặn',
  'repo.sectionWarned': 'Có cảnh báo',
  'repo.sectionPassed': 'Đạt',
  'repo.sectionNotScored': 'Chưa chấm điểm',
  'repo.sectionNotReviewed': 'Chưa review',
  'repo.sectionDraft': 'Bản nháp',
  'repo.searchAria': 'Lọc danh sách PR',
  'repo.searchPlaceholder': 'lọc theo số, tiêu đề, tác giả',
  'repo.gateFilterAria': 'Lọc theo quyết định merge',
  'repo.gateFilterAll': 'Tất cả',
  'repo.answerReplies': 'Trả lời phản hồi',
  'pr.loading': 'Đang tải PR',
  'pr.by': 'bởi {author}',
  'pr.openOnGitHub': 'mở trên GitHub',
  'pr.notReviewed': 'PR này chưa được review.',
  'pr.reviewing': 'Đang review…',
  'pr.reviewNow': 'Review ngay',
  'pr.reReview': 'Review lại',
  'pr.answerReplies': 'Trả lời phản hồi',
  'pr.tileGate': 'Gate',
  'pr.tileVerified': 'Đã xác minh',
  'pr.tileVerifiedNote': 'claim có file:line',
  'pr.tileVerdict': 'Kết luận',
  'pr.tileVerdictNote': 'mô tả PR so với code',
  'pr.tileRisk': 'Rủi ro nghiệp vụ',
  'pr.tileRounds': 'Số vòng',
  'pr.tileCost': 'Chi phí',
  'pr.pipelineLoading': 'Đang tải pipeline',
  'pr.noPipeline': 'Review này chưa có dữ liệu pipeline.',
  'pr.whyGate': 'Vì sao có kết quả này:',
  'pr.lastRun': 'lần chạy trước: exit code {code} · {at}',
  'pr.starting': 'đang khởi động…',
  'pr.blockingHeading': 'Chặn merge ({n})',
  'pr.tabClaims': 'Claim',
  'pr.tabDocs': 'Docs',
  'pr.tabImpact': 'Tác động',
  'pr.tabCallers': 'Caller',
  'pr.tabContracts': 'Contract',
  'pr.tabCrossPr': 'Cross-PR',
  'pr.tabTests': 'Test',
  'pr.tabThreads': 'Thread',
  'pr.blockContract': 'Contract',
  'pr.blockCaller': 'Caller',
  'pr.blockClaim': 'Claim',
  'pr.blockImpact': 'Tác động',
  'pr.blockDoc': 'Docs',
  'pr.blockTest': 'Test',
  'pr.emptyConfirm': 'Reviewer không có câu hỏi nào cần người trả lời.',
  'pr.answered': 'đã trả lời: {answer}',
  'pr.dropped': 'đã bỏ',
  'pr.trimmed': 'patch bị cắt bớt',
  'pr.repliesHeading': 'Phản hồi đã trả lời',
  'graph.statusDone': 'xong',
  'graph.statusRunning': 'đang chạy',
  'graph.statusFailed': 'lỗi',
  'graph.statusPending': 'chờ',
  'graph.statusSkipped': 'bỏ qua',
  'ws.tabOverview': 'Tổng quan',
  'ws.tabPipeline': 'Pipeline',
  'ws.reasonsToggle': 'Xem lý do ({n})',
  'ws.reasonsHide': 'Thu gọn lý do',
  'ws.phaseStripLabel': 'Các phase của pipeline',
  'ws.navFindings': 'Phát hiện',
  'ws.navFiles': 'File',
  'ws.noFindings': 'Không có phát hiện nào',
  'ws.collapseNav': 'Ẩn sidebar',
  'ws.expandNav': 'Hiện sidebar',
  'ws.filesViewed': '{done}/{total} đã xem',
  'ws.jumpTo': 'Nhảy tới {ref}',
  'ws.peekLoading': 'Đang tải mã nguồn',
  'ws.peekUnavailable': 'Session này không còn workspace — mở trên GitHub để xem.',
  'ws.peekClose': 'Đóng xem nhanh',
  'ws.kbdHint': 'j/k chuyển phát hiện · v đánh dấu file đã xem · Esc bỏ chọn',
  'ws.confidence': 'độ tin cậy {pct}',
  'ws.questionsHeading': 'Câu hỏi cần người trả lời',
  'ws.prunedHeading': 'Bị loại khỏi ngữ cảnh review',
  'files.viewed': 'Đã xem',
  'files.markViewed': 'Đánh dấu {path} đã xem',
  'files.summary': '{path}: +{added} −{deleted}, {findings} phát hiện',
  'files.inFile': '{n} phát hiện',
  'files.empty': 'Snapshot này không có file thay đổi.',
  'files.unanchoredHeading': 'Chưa gắn được vào diff',
  'files.noPatch': 'Không có diff dạng text (đổi tên hoặc file nhị phân)',
  'files.rawPatch': 'Hiển thị patch thô — không parse được hunk header',
  'files.patchTruncated': 'Patch đã bị cắt — còn {n} dòng, xem trên GitHub',
  'files.diffModeLabel': 'Kiểu hiển thị diff',
  'files.split': 'Split',
  'files.unified': 'Unified',
  'report.tab': 'Báo cáo',
  'report.loading': 'Đang tải báo cáo',
  'report.empty': 'Chưa có báo cáo.',
  'run.tab': 'Lần chạy',
  'run.liveHeading': 'Log trực tiếp',
  'run.idle': 'Không có review nào đang chạy.',
  'run.elapsed': 'đã chạy {t}',
  'run.costHeading': 'Chi phí theo phase',
  'run.colPhase': 'Phase',
  'run.colModel': 'Model',
  'run.colTurns': 'Số lượt',
  'run.colDuration': 'Thời gian',
  'run.colCost': 'Chi phí',
  'extras.pocHeading': 'Test chứng minh lỗi',
  'extras.pocWhy': 'Vì sao fail',
  'extras.copy': 'Copy',
  'extras.copied': 'Đã copy',
  'extras.patchHeading': 'Gợi ý sửa docs',
  'extras.patchOld': 'Hiện tại',
  'extras.patchNew': 'Đề xuất',
  'trace.heading': 'Trace của agent',
  'trace.empty': 'Session này không có transcript.',
  'extras.ticketHeading': 'Ticket',
  'extras.neutralizedBanner': 'Nội dung nghi là prompt injection trong PR đã được vô hiệu trước khi review',
  'extras.descriptionHeading': 'Bản nháp mô tả PR',
  'graph.phase.snapshot': 'Snapshot',
  'graph.phase.siblings': 'Quét PR liên quan',
  'graph.phase.describe': 'Mô tả',
  'graph.phase.claims': 'Claim',
  'graph.phase.followup': 'Phản hồi',
  'graph.phase.verify': 'Xác minh',
  'graph.phase.remediate': 'Sửa docs',
  'graph.phase.poc': 'Test PoC',
  'graph.phase.score': 'Chấm điểm',
  'graph.phase.ask': 'Xác nhận',
  'graph.phase.report': 'Báo cáo',
  'graph.metric.files': 'file',
  'graph.metric.commits': 'commit',
  'graph.metric.pruned': 'đã cắt',
  'graph.metric.scanned': 'đã quét',
  'graph.metric.overlapping': 'trùng lặp',
  'graph.metric.claims': 'claim',
  'graph.metric.docs': 'docs',
  'graph.metric.callers': 'caller',
  'graph.metric.contracts': 'contract',
  'graph.metric.gate': 'gate',
  'graph.metric.verified': 'đã xác minh',
  'graph.metric.answered': 'đã trả lời',
  'graph.metric.open': 'còn mở',
  'graph.metric.patches': 'patch',
  'graph.metric.tests': 'test',
  'graph.metric.replies': 'phản hồi',
  'config.errorAfter': ' — tạo ',
  'config.errorMid': ' cạnh repo, hoặc trỏ ',
  'config.errorEnd': ' tới nó.',
  'config.loading': 'Đang tải cấu hình',
  'config.title': 'PR Sentinel đang theo dõi những gì',
  'config.tileOrg': 'Tổ chức',
  'config.tilePollEvery': 'Chu kỳ poll',
  'config.tileGateAt': 'Ngưỡng gate',
  'config.tileGateNote': 'điểm xác minh tối thiểu',
  'config.tilePostsComments': 'Đăng comment',
  'config.tileDocPrs': 'Mở PR sửa docs',
  'config.tileRewritesBody': 'Viết lại mô tả PR',
  'config.providerHeading': 'Nhà cung cấp model',
  'config.noKeyBefore': 'Chưa có API key cho ',
  'config.noKeyMid': ' — đặt ',
  'config.noKeyAfter': ' trong ',
  'config.noKeyEnd': '. Review sẽ không chạy cho tới khi có key.',
  'config.tileProvider': 'Nhà cung cấp',
  'config.tileDeepDive': 'Phân tích sâu',
  'config.tileClaims': 'Claim',
  'config.tileSchema': 'Schema',
  'config.schemaEnforced': 'bắt buộc',
  'config.schemaPrompted': 'nhắc qua prompt',
  'config.schemaEnforcedNote': 'API tự validate JSON',
  'config.schemaPromptedNote': 'response được parse rồi tự sửa',
  'config.tileKey': 'API key',
  'config.keySet': 'đã có',
  'config.keyMissing': 'thiếu',
  'config.tileCosts': 'Chi phí',
  'config.costsTracked': 'có theo dõi',
  'config.costsUnknown': 'không rõ',
  'config.costsUnknownNote': 'không áp được hạn mức chi phí',
  'config.tokensNote': 'token chỉ đọc từ biến môi trường',
  'config.languageHeading': 'Ngôn ngữ',
  'config.uiLanguage': 'Giao diện',
  'config.uiLanguageNote': 'chỉ trình duyệt này — không đổi thứ agent viết ra',
  'config.reviewLanguage': 'Output review',
  'config.reviewLanguageNote': 'ghi vào file cấu hình; áp dụng cho mọi review, kể cả CI',
  'config.languageFootnote': 'Mã trạng thái (PASS, STALE, BROKEN…) luôn giữ tiếng Anh để dashboard khớp với comment đăng trên GitHub.',
  'config.uiLanguageAria': 'Ngôn ngữ giao diện',
  'config.reviewLanguageAria': 'Ngôn ngữ output review',
  'config.repoPlaceholderOrg': 'tên-repo hoặc owner/repo',
  'config.watchRepo': 'Theo dõi repo',
  'config.modeAria': 'Chế độ cho {repo}',
  'config.remove': 'Bỏ theo dõi',
  'lang.en': 'English',
  'lang.vi': 'Tiếng Việt',
}

export type Key = keyof typeof en
export type Vars = Record<string, string | number>

// Annotated rather than inferred so TABLES[lang][key] is `string`, not the
// union of en's literal types with vi's `string`.
export const TABLES: Record<'en' | 'vi', Record<Key, string>> = { en, vi }

/** Phase and metric labels arrive from the server at runtime (see
 *  web/metrics.py PHASES), so unlike everything above they cannot be a total
 *  map checked by the compiler. An id with no entry falls back to the server's
 *  English string. tests/test_ui_strings.py is what stops that going unnoticed. */
export function lookup(lang: 'en' | 'vi', key: string, fallback: string): string {
  const table = TABLES[lang] as Record<string, string | undefined>
  return table[key] ?? fallback
}
