/* The interface dictionary. English is the source of truth for the key set:
   `vi` is typed as Record<keyof typeof en, string>, so a key added here and
   forgotten there is a `tsc -b` error, and `npm run build` runs tsc first.

   Status vocabulary (PASS, STALE, BREAKING_API_CHANGE …) is absent on purpose:
   those are enum values from the findings schema, they appear verbatim in the
   comment posted to GitHub, and a translated dashboard label would no longer
   match the pull request it describes.

   Repo mode values (`auto`, `manual`) are absent for the same reason: they are
   the literal values an operator writes in prsentinel.yml and picks from
   Config.tsx's mode select, so Repos.tsx's "AUTO" badge (repos with no data
   yet) stays English rather than disagreeing with the YAML and the dropdown
   it mirrors. */

const en = {
  'nav.repos': 'Repos',
  'nav.config': 'Config',
  'nav.themeLight': 'Light',
  'nav.themeDark': 'Dark',
  'nav.themeSwitchToLight': 'Switch to light theme',
  'nav.themeSwitchToDark': 'Switch to dark theme',
  'nav.langSwitchToVi': 'Chuyển giao diện sang tiếng Việt',
  'nav.langSwitchToEn': 'Switch interface to English',
  'repos.bugs': '{n} bugs',
  'gate.pass': 'Clear to merge',
  'gate.warn': 'Merge with care',
  'gate.fail': 'Blocked',
  'gate.unknown': 'Not scored',
  'band.empty': 'No scored reviews yet',
  'common.loading': 'Loading',
  'common.yes': 'yes',
  'common.no': 'no',
  'common.noTitle': '(no title)',
  'citations.none': 'no evidence cited',
  'repos.error': 'Could not load repos — {detail}',
  'repos.loading': 'Loading repositories',
  'repos.title': 'Every claim, checked against the code.',
  'repos.subOne': '{n} repo reviewed',
  'repos.subMany': '{n} repos reviewed',
  'repos.subPrs': '{n} pull requests on the record',
  'repos.reviewedHeading': 'Reviewed repositories',
  'repos.emptyBefore': 'No reviews yet. Run ',
  'repos.emptyAfter': ', or add a repo on the Config page and let the poller pick it up.',
  'repos.prs': '{n} PR',
  'repos.docErrors': '{n} doc errors',
  'repos.breaking': '{n} breaking',
  'repos.testGaps': '{n} test gaps',
  'repos.verified': '{score} verified',
  'repos.waitingHeading': 'Watched, not yet reviewed',
  'repos.waitingMeta': 'Set to auto — the poller reviews its next open PR',
  'repo.loading': 'Loading repository',
  'repo.statusReviewed': 'Reviewed',
  'repo.statusReviewing': 'Reviewing now',
  'repo.statusNotReviewed': 'Not reviewed',
  'repo.tilePrs': 'PRs reviewed',
  'repo.tileVerified': 'Verified',
  'repo.tileVerifiedNote': 'claims backed by file:line',
  'repo.tileBugs': 'Bugs',
  'repo.tileBugsNote': 'failed claims + broken impact',
  'repo.tileDocErrors': 'Doc errors',
  'repo.tileBreaking': 'Breaking',
  'repo.tileBreakingNote': 'API + schema contracts',
  'repo.tileSpent': 'Spent',
  'repo.gateHeading': 'Merge decisions',
  'repo.openPrsHeading': 'Open pull requests',
  'repo.unreachable': 'GitHub is unreachable — showing pull requests from stored reviews only.',
  'repo.noOpenPrs': 'No open pull requests.',
  'repo.draft': 'draft',
  'repo.roundOne': '{n} round',
  'repo.roundMany': '{n} rounds',
  'repo.prBugs': '{n} bugs',
  'repo.prDocErrors': '{n} doc errors',
  'repo.prBreaking': '{n} breaking',
  'repo.reReview': 'Re-review',
  'repo.reviewNow': 'Review now',
  'pr.loading': 'Loading the PR',
  'pr.by': 'by {author}',
  'pr.openOnGitHub': 'open on GitHub',
  'pr.notReviewed': 'This pull request has not been reviewed yet.',
  'pr.reviewing': 'Reviewing…',
  'pr.reviewNow': 'Review now',
  'pr.reReview': 'Re-review',
  'pr.answerReplies': 'Answer replies',
  'pr.tileGate': 'Gate',
  'pr.tileVerified': 'Verified',
  'pr.tileVerifiedNote': 'claims with file:line',
  'pr.tileVerdict': 'Verdict',
  'pr.tileVerdictNote': 'PR description vs code',
  'pr.tileRisk': 'Business risk',
  'pr.tileRounds': 'Rounds',
  'pr.tileCost': 'Cost',
  'pr.pipelineHeading': 'Pipeline',
  'pr.pipelineLoading': 'Loading the pipeline',
  'pr.noPipeline': 'No pipeline data for this review yet.',
  'pr.whyGate': 'Why this gate:',
  'pr.lastRun': 'last run exit {code} · {at}',
  'pr.inProgressHeading': 'Review in progress',
  'pr.starting': 'starting…',
  'pr.blockingHeading': 'Blocking ({n})',
  'pr.tabClaims': 'Claims',
  'pr.tabDocs': 'Docs',
  'pr.tabImpact': 'Impact',
  'pr.tabCallers': 'Callers',
  'pr.tabContracts': 'Contracts',
  'pr.tabTests': 'Tests',
  'pr.tabThreads': 'Threads',
  'pr.tabConfirm': 'Confirm',
  'pr.tabContext': 'Context',
  'pr.blockContract': 'Contract',
  'pr.blockCaller': 'Caller',
  'pr.blockClaim': 'Claim',
  'pr.blockImpact': 'Impact',
  'pr.blockDoc': 'Doc',
  'pr.blockTest': 'Test',
  'pr.emptyClaims': 'The description made no verifiable claims.',
  'pr.emptyDocs': 'No documentation related to this change was found.',
  'pr.emptyImpact': 'No requirement was traced to this change.',
  'pr.emptyCallers': 'Nothing outside this diff calls the changed code.',
  'pr.emptyContracts': 'No API, schema, type or proto contract was touched.',
  'pr.emptyTests': 'No test coverage was assessed for this change.',
  'pr.emptyThreads': 'No review comments to re-check.',
  'pr.emptyConfirm': 'The reviewer had no questions for a human.',
  'pr.emptyContext': 'The whole diff went into the review — nothing was trimmed.',
  'pr.uncovered': 'uncovered: {case} → {where}',
  'pr.answered': 'answered: {answer}',
  'pr.dropped': 'dropped',
  'pr.trimmed': 'patch trimmed',
  'pr.repliesHeading': 'Replies answered',
}

const vi: Record<keyof typeof en, string> = {
  'nav.repos': 'Kho mã',
  'nav.config': 'Cấu hình',
  'nav.themeLight': 'Sáng',
  'nav.themeDark': 'Tối',
  'nav.themeSwitchToLight': 'Chuyển sang giao diện sáng',
  'nav.themeSwitchToDark': 'Chuyển sang giao diện tối',
  'nav.langSwitchToVi': 'Chuyển giao diện sang tiếng Việt',
  'nav.langSwitchToEn': 'Switch interface to English',
  'repos.bugs': '{n} lỗi',
  'gate.pass': 'Sẵn sàng merge',
  'gate.warn': 'Merge có cân nhắc',
  'gate.fail': 'Bị chặn',
  'gate.unknown': 'Chưa chấm điểm',
  'band.empty': 'Chưa có review nào được chấm điểm',
  'common.loading': 'Đang tải',
  'common.yes': 'có',
  'common.no': 'không',
  'common.noTitle': '(không có tiêu đề)',
  'citations.none': 'không có bằng chứng nào được dẫn',
  'repos.error': 'Không tải được danh sách kho mã — {detail}',
  'repos.loading': 'Đang tải danh sách kho mã',
  'repos.title': 'Mọi tuyên bố đều được đối chiếu với code.',
  'repos.subOne': '{n} kho mã đã review',
  'repos.subMany': '{n} kho mã đã review',
  'repos.subPrs': '{n} pull request trong hồ sơ',
  'repos.reviewedHeading': 'Kho mã đã review',
  'repos.emptyBefore': 'Chưa có review nào. Chạy ',
  'repos.emptyAfter': ', hoặc thêm một kho mã ở trang Cấu hình rồi để bộ quét tự nhận.',
  'repos.prs': '{n} PR',
  'repos.docErrors': '{n} lỗi tài liệu',
  'repos.breaking': '{n} phá vỡ tương thích',
  'repos.testGaps': '{n} lỗ hổng test',
  'repos.verified': '{score} đã xác minh',
  'repos.waitingHeading': 'Đang theo dõi, chưa review',
  'repos.waitingMeta': 'Đặt chế độ auto — bộ quét sẽ review PR mở tiếp theo',
  'repo.loading': 'Đang tải kho mã',
  'repo.statusReviewed': 'Đã review',
  'repo.statusReviewing': 'Đang review',
  'repo.statusNotReviewed': 'Chưa review',
  'repo.tilePrs': 'PR đã review',
  'repo.tileVerified': 'Đã xác minh',
  'repo.tileVerifiedNote': 'tuyên bố có dẫn file:line',
  'repo.tileBugs': 'Lỗi',
  'repo.tileBugsNote': 'tuyên bố sai + tác động hỏng',
  'repo.tileDocErrors': 'Lỗi tài liệu',
  'repo.tileBreaking': 'Phá vỡ tương thích',
  'repo.tileBreakingNote': 'hợp đồng API + schema',
  'repo.tileSpent': 'Đã chi',
  'repo.gateHeading': 'Quyết định merge',
  'repo.openPrsHeading': 'Pull request đang mở',
  'repo.unreachable': 'Không kết nối được GitHub — chỉ hiện pull request từ review đã lưu.',
  'repo.noOpenPrs': 'Không có pull request nào đang mở.',
  'repo.draft': 'nháp',
  'repo.roundOne': '{n} vòng',
  'repo.roundMany': '{n} vòng',
  'repo.prBugs': '{n} lỗi',
  'repo.prDocErrors': '{n} lỗi tài liệu',
  'repo.prBreaking': '{n} phá vỡ tương thích',
  'repo.reReview': 'Review lại',
  'repo.reviewNow': 'Review ngay',
  'pr.loading': 'Đang tải PR',
  'pr.by': 'bởi {author}',
  'pr.openOnGitHub': 'mở trên GitHub',
  'pr.notReviewed': 'Pull request này chưa được review.',
  'pr.reviewing': 'Đang review…',
  'pr.reviewNow': 'Review ngay',
  'pr.reReview': 'Review lại',
  'pr.answerReplies': 'Trả lời phản hồi',
  'pr.tileGate': 'Cổng merge',
  'pr.tileVerified': 'Đã xác minh',
  'pr.tileVerifiedNote': 'tuyên bố có file:line',
  'pr.tileVerdict': 'Kết luận',
  'pr.tileVerdictNote': 'mô tả PR đối chiếu code',
  'pr.tileRisk': 'Rủi ro nghiệp vụ',
  'pr.tileRounds': 'Số vòng',
  'pr.tileCost': 'Chi phí',
  'pr.pipelineHeading': 'Quy trình',
  'pr.pipelineLoading': 'Đang tải quy trình',
  'pr.noPipeline': 'Chưa có dữ liệu quy trình cho review này.',
  'pr.whyGate': 'Vì sao có kết quả này:',
  'pr.lastRun': 'lần chạy trước thoát {code} · {at}',
  'pr.inProgressHeading': 'Đang review',
  'pr.starting': 'đang khởi động…',
  'pr.blockingHeading': 'Chặn merge ({n})',
  'pr.tabClaims': 'Tuyên bố',
  'pr.tabDocs': 'Tài liệu',
  'pr.tabImpact': 'Tác động',
  'pr.tabCallers': 'Nơi gọi',
  'pr.tabContracts': 'Hợp đồng',
  'pr.tabTests': 'Test',
  'pr.tabThreads': 'Thảo luận',
  'pr.tabConfirm': 'Xác nhận',
  'pr.tabContext': 'Ngữ cảnh',
  'pr.blockContract': 'Hợp đồng',
  'pr.blockCaller': 'Nơi gọi',
  'pr.blockClaim': 'Tuyên bố',
  'pr.blockImpact': 'Tác động',
  'pr.blockDoc': 'Tài liệu',
  'pr.blockTest': 'Test',
  'pr.emptyClaims': 'Mô tả không đưa ra tuyên bố nào kiểm chứng được.',
  'pr.emptyDocs': 'Không tìm thấy tài liệu nào liên quan tới thay đổi này.',
  'pr.emptyImpact': 'Không truy được yêu cầu nào tới thay đổi này.',
  'pr.emptyCallers': 'Không có chỗ nào ngoài diff này gọi tới code đã đổi.',
  'pr.emptyContracts': 'Không đụng tới hợp đồng API, schema, kiểu hay proto nào.',
  'pr.emptyTests': 'Chưa đánh giá độ phủ test cho thay đổi này.',
  'pr.emptyThreads': 'Không có comment review nào cần kiểm tra lại.',
  'pr.emptyConfirm': 'Reviewer không có câu hỏi nào cho người.',
  'pr.emptyContext': 'Toàn bộ diff đã vào review — không cắt bỏ gì.',
  'pr.uncovered': 'chưa phủ: {case} → {where}',
  'pr.answered': 'đã trả lời: {answer}',
  'pr.dropped': 'đã bỏ',
  'pr.trimmed': 'đã cắt bớt patch',
  'pr.repliesHeading': 'Phản hồi đã trả lời',
}

export type Key = keyof typeof en
export type Vars = Record<string, string | number>

// Annotated rather than inferred so TABLES[lang][key] is `string`, not the
// union of en's literal types with vi's `string`.
export const TABLES: Record<'en' | 'vi', Record<Key, string>> = { en, vi }

/** Phase and metric labels arrive from the server at runtime (see
 *  web/metrics.py PHASES), so unlike everything above they cannot be a total
 *  map checked by the compiler. An id with no entry falls back to the server's
 *  English string. tests/test_ui_strings.py is what stops that going unnoticed. */
export function lookup(lang: 'en' | 'vi', key: string, fallback: string): string {
  const table = TABLES[lang] as Record<string, string | undefined>
  return table[key] ?? fallback
}
